### ISSUE TITLE
重复TraceId

### ISSUE THREAD

**Issue by jackguan666** [Redick01/log-helper#85]
请问如何修改TraceId的方式，我在网关接入后，并发时，很多请求都是用同一个TraceId。

![WX20240318-221041@2x](https://github.com/Redick01/log-helper/assets/9218958/e22c1aeb-ceb0-4dc8-ba58-72dcd42e116d)

**Comment by Redick01** [comment]
引用的依赖版本是多少

**Comment by jackguan666** [comment]
> 引用的依赖版本是多少

log-helper-spring-boot-starter-scg：1.0.5-RELEASE
spring-cloud-starter-gateway：3.18

**Comment by Redick01** [comment]
> > 引用的依赖版本是多少
> 
> log-helper-spring-boot-starter-scg：1.0.5-RELEASE spring-cloud-starter-gateway：3.18

确实有你描述的问题，我这边把代码更新了下，你可以fork到自己本地打包改版本号试一下
